/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cwzeng' at '8/20/16 9:38 PM' with Gradle 2.14
 *
 * @author cwzeng, @date 8/20/16 9:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
